### ISSUE TITLE
Discussion: Support React Native

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#105]
If we were to use react primitives rather than react dom elements, we could support React Native

**Comment by penx** [comment]
this is currently a discussion point rather than a definite plan, would we lose anything semantic-wise or accessibility-wise if we were to do this?

**Comment by penx** [comment]
Also of interest is that if we were to use react primitives, we would be able to consider compatibility with [react-sketchapp](https://github.com/airbnb/react-sketchapp)

**Comment by penx** [comment]
The top nav currently uses the adjacent sibling selector to support opening + closing when JavaScript is disabled, I can't think of how this would be compatible with React Native.

**Comment by Loque-** [comment]
It could fallback to using CSS with the sibling selector if JS is not available?

**Comment by stevesims** [comment]
potentially of some relevance here:
https://github.com/necolas/react-native-web

**Comment by penx** [comment]
> This library was largely inspired from the work done by Nicolas Gallager and his great work on the react-native-web library. A few of the files in this repo are even copied directly from his project.


https://github.com/lelandrichardson/react-primitives

**Comment by penx** [comment]
Perhaps worth looking in to https://github.com/kristerkari/react-native-sass-transformer if we consume govuk-frontend scss in future
