### ISSUE TITLE
Footer: No way to create Footer without OGL

### ISSUE THREAD

**Issue by salivity** [govuk-react/govuk-react#1059]
Not everyone is going to be using the OGL how can i create a custom message to overwrite the text and link.

**Comment by Loque-** [comment]
I am not sure I understand the question, would you be able to provide more context? A codesandbox link can also speed up the process a lot. Cheers!

**Comment by penx** [comment]
I think this references the OGL message in the footer component

https://govuk-react.github.io/govuk-react/?path=/story/footer--with-navigation-and-meta

**Comment by penx** [comment]
I think we always render <MetaContainer> in the Footer, which in turn always renders <Licence> so there's not currently a way to hide this with the Footer component.

**Comment by penx** [comment]
I suggest that we add a licence prop to Footer that:

- if undefined, shows the default licence
- if false, hides the licence
- if a react element or string, renders the react element or string

**Comment by penx** [comment]
A PR for this would be welcomed, else I may get to it later this year

**Comment by penx** [comment]
@salivity would you like to send a PR for this?

**Comment by bartmika** [comment]
+1

**Comment by domdomegg** [comment]
> A PR for this would be welcomed, else I may get to it later this year

I've opened https://github.com/govuk-react/govuk-react/pull/1072 which I think resolves this
