### ISSUE TITLE
Logo font is different

### ISSUE THREAD

**Issue by cherrelleM1** [govuk-react/govuk-react#1064]
**Describe the bug**
The logo seems different from the design and the main site

**To Reproduce**
1. Go to ['govuk-react storybook example application'](https://govuk-react.github.io/govuk-react/?path=/story/example-application--example-application)
2. Compare the logo to the ['Design Website'](https://design-system.service.gov.uk/) and ['gov.uk main site'](https://www.gov.uk/)
3. The govuk-react logo is more thicker and has 'nta' font. The Design and Main website both have "GDS Transport" font

**Expected behavior**
Expected the logo to be the same as the Design System and the Main gov.uk site.

**Screenshots**
Design System logo
![image](https://user-images.githubusercontent.com/98096592/159481412-6b13eb5a-e610-40e0-8800-a800f2e0ccdf.png)

gov.uk main site logo
![image](https://user-images.githubusercontent.com/98096592/159481483-daa7f282-625e-4acb-a149-26aafeccaf93.png)

govuk-react app logo
![image](https://user-images.githubusercontent.com/98096592/159481563-cf0c6a81-4081-4d92-a54d-8065e85e58e5.png)

**Desktop (please complete the following information):**
 - Windows 10 
 - Browser: Chrome

**Comment by Loque-** [comment]
Hi there, have you read this? https://github.com/govuk-react/govuk-react/issues/272 it is linked from the readme.md; https://github.com/govuk-react/govuk-react#about-the-gds-font

**Comment by cherrelleM1** [comment]
@Loque- 

Just saw it. Thanks for your comment!
