### ISSUE TITLE
e2e testing

### ISSUE THREAD

**Issue by marksy** [govuk-react/govuk-react#124]
Maybe look into integrating cypress? https://www.cypress.io/

**Comment by penx** [comment]
I could see how this would work in a peer project, e.g. the example site, and running some automated tests on the peer project before incrementing the version of govuk-react that is used.

But I'm unclear on the advantages of using it for a component library.

I did however find this https://medium.com/@mtiller/testing-react-components-using-storybook-and-cypress-1689a27f55aa

**Comment by penx** [comment]
also see #65
