### ISSUE TITLE
Should Glamorous be a dependency rather than peerDependency

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#177]
This ticket is to discuss potentially moving Glamorous from peerDependencies to dependencies.

This was initially raised on Slack by @lennym:

> You could achieve something similar though (_I think_) by moving the peer dependency to a main dependency, but with the same leniency for versions. npm would dedupe to the parent project’s version if it satisfies (which it’d need to anyway to satisfy the peer dependency) but would install latest if no parent version were present.

**Comment by penx** [comment]
I think it's appropriate to use peer dependencies when you are stating:

1.  no more than 1 of this dependency should ever be included in an application
2. this package is solely designed to be used as a dependency

As far as I'm aware, glamor does not work if you have multiple instances loaded in the browser, so I think it's safe to assume multiple instances of Glamorous could also cause issues. As such, I think it's preferable to keep it in peer dependencies.

On the other hand, if we were to switch to another CSSinJS solution such as styled-components, I understand the desire to have peer projects automatically update, however if a core change like this was made I would expect to update the major version number and would want peer projects to be aware of the change.

**Comment by penx** [comment]
Both Atlassian AtlasKit and Auth0 Cosmos have styled-components as a dependency rather than peerDependency

https://bitbucket.org/atlassian/atlaskit-mk-2/src/71efe2fbeb26866ef6f29d81d43e31978184460c/packages/core/avatar/package.json?at=master

https://www.npmjs.com/package/auth0-cosmos?activeTab=dependencies

**Comment by penx** [comment]
Issue raised against AtlasKit here https://bitbucket.org/atlassian/atlaskit-mk-2/issues/24/styled-components-should-be-a-peer

**Comment by stevesims** [comment]
Closing - we no longer use glamorous, and have had no reported problems using peerDependencies
