### ISSUE TITLE
turn the HOC into a monorepo

### ISSUE THREAD

**Issue by marksy** [govuk-react/govuk-react#187]
currently the HOC components are all in one repo, `@govuk-react/hoc` but they should be in their own repositories `@govuk-react/with-white-space`

**Comment by stevesims** [comment]
Closing this...

We've mostly moved away from HOCs in govuk-react.  The `asAnchor` and `withWhiteSpace` HOCs have both been deprecated, and should be removed soon.

This leaves `asPaginationItem`, which itself needs a rethink, and `deprecate`.
