### ISSUE TITLE
Warnings during yarn install

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#215]
```
warning " > @storybook/react@3.4.1" has unmet peer dependency "babel-runtime@>=6.0.0".
warning "@govuk-react/storybook-components > @storybook/react > babel-loader@7.1.4" has incorrect peer dependency "babel-core@6".
warning " > webpack-cli@2.0.14" has incorrect peer dependency "webpack@^4.0.0".
```

**Comment by gavinorland** [comment]
Hi - I have just had an initial look at this and found https://github.com/storybooks/storybook/issues/2303. If we look in `node_modules/@storybook/react/package.json` we do see that `babel-runtime` is defined as both a dependency and a peer dependency, which looks a bit odd. That's probably something we can't fix, but maybe we could try bumping up some of our module versions - for example we specify `webpack-cli ^2.0.12`, `2.0.14` is installed but `3.0.3` is the latest? Just some thoughts. Let's see.

**Comment by penx** [comment]
I don't think we need an issue to track yarn install warnings
