### ISSUE TITLE
Heading subclasses

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#224]
Our heading components should probably export sub classes like this:

```js
const Heading = styled.h1`
  ...
`

Heading.h1 = Heading
Heading.h2 = Heading.extendWith('h2')
Heading.h3 = Heading.extendWith('h3')
Heading.h4 = Heading.extendWith('h4')
Heading.h5 = Heading.extendWith('h5')
Heading.h6 = Heading.extendWith('h6')
Heading.Link = Heading.extendWith(Link)

export default Header
```
https://github.com/styled-components/styled-components/issues/246#issuecomment-297861297

**Comment by penx** [comment]
Probably use capital H1 etc. as it's a component

**Comment by stevesims** [comment]
Closing.

Heading has been doing this for a while - except for `Link` - but that's also achievable by placing a `Link` inside a `Heading` component
