### ISSUE TITLE
Port of govuk-frontend or implementation of the GOV.UK Design System?

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#235]
> GOV.UK Frontend is not an implementation of the GOV.UK Design System, it is a core part of the Design System, so govuk-react would therefore be a port of GOV.UK Frontend.

See

https://github.com/penx/govuk-react/pull/234#issuecomment-384920363

Need to discuss and clarify in readme

**Comment by penx** [comment]
govuk-react is currently an implementation of GOV.UK Design System with the intention of directly using the GOV.UK Frontend source code in future, at which point it will become a port of GOV.UK Frontend

**Comment by penx** [comment]
Also worth noting that govuk-react goes beyond a port, in that it provides additional functional components that a React App may need, e.g. LoadingBox.

**Comment by stevesims** [comment]
Since this comment was written, we've been more closely following govuk-frontend, but we do still have additional components that are not present there.

I believe our existing description in `README.md` adequately describes things, and that we can probably close this issue.
