### ISSUE TITLE
Add chai-enzyme to improve tests

### ISSUE THREAD

**Issue by Loque-** [govuk-react/govuk-react#253]
Chai enzyme looks like it could be a helpful addition to the test CI setup on this project. I am personally interested in the output for when tests fail to help us identify and resolve issues quickly. Inspired from this post: http://wleecarter.com/post/three-ways-to-see-what-enzyme-is-rendering/

**Comment by Loque-** [comment]
Of course! I am less interested in migrating the syntax TBF (as the tests will still run), and more interested in having it available for when tests fail to assist with debugging.

**Comment by penx** [comment]
moving away from enzyme
