### ISSUE TITLE
Normalise form elements and create examples with final form

### ISSUE THREAD

**Issue by Loque-** [govuk-react/govuk-react#281]
stub for more details here, feel free to edit / update

**Comment by penx** [comment]
Not sure what is meant by normalise, but this may cross over with https://github.com/UKHomeOffice/govuk-react/issues/164

**Comment by Loque-** [comment]
Yes, nice one, I will fill this out soon - specifically it was about normalising props so that they were consistent (in what was required and passed down) in order to help their implementation with and without final form, but, I think this tasks ties in really well with #164 as a solid naming convention and structure will really help round off the form field implementation in the component library.

**Comment by penx** [comment]
closing as duplicate: 

Normalise form elements: #164
Create examples with final form: #249
