### ISSUE TITLE
Messaging for what versions of upstream CSS we're in sync with

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#312]
We should include messaging in our readme file to make it clear what version of the upstream govuk styles we are in sync with

**Comment by penx** [comment]
I don't think we're in sync with any, nor do I expect we will be (due to required maintenance overhead) unless we're automating it somehow e.g. via govuk-frontend-react

**Comment by penx** [comment]
the aim is to be in line with the latest styles whenever we do work, of course that makes things out of sync but without significant dev input I don't think we have an option
