### ISSUE TITLE
checkbox is selected when clicking outside label/input

### ISSUE THREAD

**Issue by hom-bahrani** [govuk-react/govuk-react#358]
odd behaviour with the checkbox, observed by our QA. When you click to the right of the checkbox much further to the right of the page the checkbox can be selected / deselected. this results in accidental selection
![checbox](https://user-images.githubusercontent.com/8465628/42134795-09915a50-7d3a-11e8-89e9-642b89d84697.gif)

**Comment by Loque-** [comment]
Ah nice spot, classic one this - need to use `display: inline-block;` here: https://github.com/UKHomeOffice/govuk-react/blob/master/components/radio/src/index.js#L13

We can add a quick fix for this, but, we might also be able to fly through all the form elements next week also. If anyone needs something immediately this would work;

```js
import styled from 'react-emotion';
import Radio from '@govuk-react/radio';

const RadioField = styled(Radio)({
  display: 'inline-block',
})
```
