### ISSUE TITLE
Fix Codecov CI integration

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#398]
CodeCov seems to be correctly commenting on pull requests most of the time:

- https://github.com/UKHomeOffice/govuk-react/pull/396
- https://github.com/UKHomeOffice/govuk-react/pull/394

But sometimes doesn't:

- https://github.com/UKHomeOffice/govuk-react/pull/397

Also in the list of checks, codecov does not get marked as complete, with the message "codecov/patch Expected — Waiting for status to be reported"

<img width="839" alt="screen shot 2018-09-05 at 10 44 15" src="https://user-images.githubusercontent.com/1027024/45085468-aa47a480-b0f8-11e8-9676-5369f1dcf7f5.png">

https://github.com/UKHomeOffice/govuk-react/pull/392

**Comment by thislooksfun** [comment]
I can confirm that `codecov/patch` and `codecov/project` often hang for much longer than expected, often hours after the rest of the checks are complete and the coverage has been uploaded.
