### ISSUE TITLE
Ensure HOCs are named with camelCase and located in correct directory

### ISSUE THREAD

**Issue by gavinorland** [govuk-react/govuk-react#402]
As per [@penx's comment](https://github.com/UKHomeOffice/govuk-react/pull/401#discussion_r215374970).

The components can be moved from `packages/storybook-components` into `packages/hoc`.

**Comment by penx** [comment]
I think file names should be lowercase, but the name we refer to them as should be camelCase.

Most will have been deprecated shortly.

**Comment by penx** [comment]
I think `deprecate` is the last HOC left now that we have #828 and #645
