### ISSUE TITLE
Using this project in production

### ISSUE THREAD

**Issue by opensourcegeek** [govuk-react/govuk-react#413]
First of all, thanks for this effort - I'm learning a lot reading through your code. 

I'd like to clarify few things like,
    - If this project is production ready
    - If so, are there any example production sites already using it please? 
    - Is accessibility addressed for all components?

I'd like to use this project instead of hand wrapping elements as react components if possible. Any help would be really great. Thanks.

**Comment by Loque-** [comment]
Hi there, I'm hoping someone else also responds, but in my opinion;

 - I would be happy using this in production, however I would add contingency for some issues as I go when implementing it as I only know of projects in development and not deployed currently. [This reference might be helpful](https://codesandbox.io/s/x917knwm4z), but is not complete. There is a separate repo setup with the goal of rendering all the components in a demo site that is updated via greenkeeper but it hasn't had enough development to completely realise itself yet, something for the future for sure.
 - Accessibility considerations have only been copied from the GDS components that this project replicates, so they are yet to be run through any automated accessibility tool, or, more critically, yet to be put on a site which is then browsed with an accessible browser such as JAWS... I personally don't believe the extent of any accessibility adjustments that might need to be made would be large 9and maybe none at all), but that is only a guess from me currently.

One point that might be useful to note is that form components, whilst good enough, could be better in my opinion, and I hope to be able to develop these further (although I feel like I have been saying this for a while now!).

Hope that helps. To reiterate on my first point however, I would be happy using this in production, and encourage it, the components have tests, have visual regression in the repo, are maintained, and I can't think of a better route for building GDS site using React.

**Comment by opensourcegeek** [comment]
Cheers for taking time to explain. I'll consult with my team and see how we can take it forward.
