### ISSUE TITLE
Provide examples on how to extend the component

### ISSUE THREAD

**Issue by timarney** [govuk-react/govuk-react#435]
I see in some of the components "provide examples on how to extend the component"
` * - Remove `errorColor` and provide examples on how to extend the component`

Is this already possible?

If not ...
It would be nice to be able to get access to either the styles (directly) or the styled css i.e. StyledButton

https://github.com/UKHomeOffice/govuk-react/blob/master/components/button/src/index.js

Maybe something like
https://github.com/emotion-js/emotion/issues/109#issuecomment-313829050

To allow for overriding button colours etc...

**Comment by penx** [comment]
@timarney we've had a few discussions on this internally.

On the one side, if we say that any CSS property could be overridden by the parent application, this is pretty broad and makes it hard to track breaking changes (e.g. if a parent application started overriding margin or display properties, and then we changed a component to start using flexbox or CSS Grid, then this could break the peer application). My preference is to not encourage specific CSS overrides by a peer application, especially while the library is still evolving.

However, we would want the component library to support what peer applications need.

My personal preference is that, if an override is needed (such as button colour), these are added case by case as features/props to the components.

I would be interested to hear how other component libraries handle this. We have a few listed in the project readme.

Does this make sense to you? If you have any further thoughts on this then let us know. If you want, we could set up a call some time.

**Comment by penx** [comment]
@marksy @Loque- @stevesims @gavinorland may have some thoughts on this

**Comment by timarney** [comment]
@penx thanks for the quick response.

Some control over the font and colours would be a great starting point.

I'll gather thoughts and ideas from some interested people on my end and yes a call at some point would be good.

We took a copy and paste approach here:
**Example:**
https://github.com/cds-snc/ircc-rescheduler/blob/master/src/components/forms/Button.js#L89

**URL**:
https://vancouver.rescheduler-dev.cds-snc.ca/register

> we would want the component library to support what peer applications need

There's another project as CDS currently being worked on,  that is looking at using this repo "more directly"  likely a good use case but perhaps too early.

**Comment by timarney** [comment]
Fantastic all - I'll be meeting a few people to discuss on my end later today.  

I've heard of but haven't tried ` polished` yet.  Will have a look.

@stevesims we're in Ottawa, Ontario ... can look into arranging something :)

Exciting stuff.

**Comment by timarney** [comment]
@penx 

> I would be interested to hear how other component libraries handle this. We have a few listed in the project readme.

Figured I would ping the creator of emotion 
https://twitter.com/tkh44/status/1055890071813943296

He notes https://primer.style/components/docs/primer-theme as one to look at.

**Comment by penx** [comment]
I briefly started looking at using styled-system a while back:

https://github.com/penx/govuk-styled-system
https://www.npmjs.com/package/govuk-styled-system

My understanding is that we should make a standalone govuk-styled-system repository working first, then we could make this project use it.

**Comment by timarney** [comment]
I think styled-system (or something like it) would be the most flexible approach.  Defaults + easy overrides if needed.  Personally I would like to explore this route.

For now - one of the teams at CDS is going to fork this repo and play around with a passing props type of approach.  We'll see how that goes.

Like the simple override properties part here:
```
let imageStyle = Object.assign(
      {},                               // target (starting with)
      { ...sensible defaults... },  // some pre-defined default React inline-style for the component
      this.props.style              // allow consumers to override properties
    );
```

Overall would be worth a call to discuss pain points such as getting styling updates from upstream, fonts etc...

**Comment by pcraig3** [comment]
Interesting discussion! Thanks for being so engaged!

I don't have a specific implementation to suggest, but I figured I would throw in a little anecdote, spurred by reading @penx's [comment above](https://github.com/UKHomeOffice/govuk-react/issues/435#issuecomment-433359501).

Granted it was a couple years back now, but when I was working on the [Digital Marketplace](https://www.digitalmarketplace.service.gov.uk/), I was going to the frontend meetings pretty regularly.  One of the discussions that came up was whether or not to allow the `disabled` attribute to be set on <button> elements, because typically disabling buttons is a bad idea. 
The decision that was reached was “let people do whatever they want, but warn them _strongly_ against disabling buttons, which they do both [in govuk-elements](https://govuk-elements.herokuapp.com/buttons#button-disabled
) and in [the design system](https://design-system.service.gov.uk/components/button/#disabled-buttons).

Effectively, it was agreed that it was better to err on the side of developer flexibility (ie, allowing developers more freedom) and warn against potential pitfalls rather than being overly restrictive.

Again, not trying to suggest anything specific and it's great to see the conversation develop, just thought that might be helpful context.

**Comment by stevesims** [comment]
Current update is that we added support for changing button colours a while back.

Many, if not most of our components do allow re-styling via simply passing the component to `styled` (whether using the older emotion release, or the new forthcoming styled-components based version).  There may however be some problems when doing that - if problems are found though fixes should be relatively simple, so filing issues should result in quick fixes.

Adding in proper support for theming however would be a good and sensible thing to do though.  At present we've not given this much thought - just not had quite enough time.  Part of the issue would be how to arrange themes - at present the data that comprises the "theme" is split between @govuk-react/constants and govuk-colours, so this would need a rethink.

**Comment by penx** [comment]
due to the overhead of maintaining theming in govuk-react and available time of the current maintainers, we're not planning on tackling theming

also @timarney I only just today realised you made react-app-rewired 👍

**Comment by penx** [comment]
@timarney are you still using govuk-react?

**Comment by timarney** [comment]
@penx thanks for the ping

### Maintaining...

>  overhead of maintaining/supporting + available time of the current maintainers

Makes sense 

### Update on our end

We're currently not using `govuk-react` but continue utilizing bits and pieces of gov uk components in our work.  Given the pandemic our work has shifted around to say the least but a design system being talked about.  

This project forms project is the most active we have re: react components https://github.com/cds-snc/platform-forms-client/tree/main/components/forms

###  react-app-rewired

:)
