### ISSUE TITLE
Passing props to sub elements

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#436]
We've had feedback that it would be nice to pass props to specific child elements of a component.

I'm not sure we should be doing this broadly, instead just providing where there are required features/props, but need to think a bit more about it.

If there is a clear solution to this that doesn't involve a code change, we should add it to an FAQ 

> The biggest issue has probably been passing props/attributes through to nested child elements when the govuk-react component is made up of multiple HTML elements. In some cases, anything we added would be passed to the correct place by default, or there would be a `meta` attribute that we could use to pass data to the correct places. In other cases though, there was no way to do what we needed until a change to the library had been made to implement our specific request. For example passing `name` attributes to the ‘day’, ‘month’, and ‘year’ input fields for Date.
It would be nice if there was a clean way to pass whatever you want through to whichever element

**Comment by stevesims** [comment]
My feeling is that one way to accomplish this is to have atoms used within complex components exposed, and used via props.  This would allow styles on those atoms to be overridden, and then for the custom styled versions of the atoms to be used.

For example, a complex component with customisable elements could look like this:
```jsx
// Atoms would usually be imported from separate src files - put here for simplicity
const FirstAtom = styled('div')({ ...firstStyles });
const SecondAtom = styled('div')({ ...secondStyles });

const ComplexComponent = ({
  firstComponent: FirstComponent,
  secondComponent: SecondComponent,
  ...props
}) => (
  <Container {...props}>
    <FirstComponent />
    <SecondComponent />
  </Container>
);

ComplexComponent.defaultProps = {
  firstComponent: FirstAtom,
  secondComponent: SecondAtom,
};

ComplexComponent.FirstAtom = First;
ComplexComponent.SecondAtom = Second;

export default ComplexComponent;
```

In use to get default styling you'd just use:
```
<ComplexComponent />
```

To add custom styles to `FirstAtom`, you'd do something like:
```jsx
const customFirstAtom = styled(ComplexComponent.FirstAtom)({ ...customStyles });

export default () => (
  <ComplexComponent firstComponent={customFirstAtom} />
);
```

**Comment by penx** [comment]
If we want to build a component that optionally allow props that are forwarded to atoms, this pattern may work:

i.e. inside a component that has a prop 'label' and an atom called Label:
```jsx
      <Label
        {...(isString(label) || React.isValidElement(label) ? { children: label } : label)}
      />
```

If label is passed as a string or as a React Element, pass down to Label as the children prop.
However, if label is an object, spread them as props to Label.

This allows the user to either do any of the following:

```jsx
<MyComponent label="Label" />
<MyComponent label={<>Label</>} />
<MyComponent label={{children: "Label", className: "custom-class" />
```

**Comment by penx** [comment]
or, to allow for non string value types as children:

```jsx
      <Label
        {...(typeof label !== 'object' || React.isValidElement(label)
          ? { children: label }
          : label)}
      />
```

**Comment by penx** [comment]
or just split in to 2 props, `label` and `labelProps`

**Comment by penx** [comment]
If/when we do this I would prefer a component composition/compound component approach, and this would need to be tackled on a per component basis when there is need.
