### ISSUE TITLE
Reconsider Prettier

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#440]
Prettier was removed here

https://github.com/UKHomeOffice/govuk-react/pull/89

Unfortunately I didn't note down why I removed it and can't remember why. I have a feeling that some auto fix rules were conflicting, though perhaps this works better now anyway,.

Maybe we should give it another go, mainly to stop comments like [this](https://github.com/UKHomeOffice/govuk-react/pull/420#discussion_r228581925).

**Comment by stevesims** [comment]
Prettier has now been re-introduced.  Closing
