### ISSUE TITLE
Description is not showing up in error summary component

### ISSUE THREAD

**Issue by opensourcegeek** [govuk-react/govuk-react#448]
I've got a problem where description is not showing up in error-summary component (React 16.6.0 and govuk-react 0.2.12 on chrome/firefox). It's a vanilla create-react-app with just error summary component on. Please see the code below,

```jsx
class App extends Component {
  render() {
    const description = "Some description";
    const errors = [
      {
        targetName: 'national-insurance-number',
        text: 'National Insurance number error',
      }
    ];
    return (
      <div className="App">
        <ErrorSummary 
          heading={'Some header'}
          description={description}
          errors={errors}
        />
        <InputField
          name="national-insurance-number"
          hint="It’s on your National Insurance card, benefit letter, payslip or P60."
        >
        National Insurance number
        </InputField>
      </div>
    );
  }
}
```
Weird thing is, when I try code on codesandbox, it seems to work. (https://20887m4y4y.codesandbox.io/ExampleOnePage). Any ideas please?

**Comment by penx** [comment]
Can you try to recreate the issue in a github repository and link to it? Commit your package/yarn lock so we have the same dependency tree to recreate. Hard to help if the code sandbox works!

**Comment by opensourcegeek** [comment]
@penx When I set description with back ticks (`), I can see it appear in description but not others. When I inspect the actual paragraph element it has no content however I can see it getting passed along to `StyledParagraph` - something wrong with react markdown perhaps?

**Comment by Loque-** [comment]
I just checked this out, and I can break the codesandbox version by updating react-markdown to version 4.x

**Comment by opensourcegeek** [comment]
@Loque- cheers, I did get that working after downgrading to 3.3.2. Not sure if you want to keep this issue open or track react-markdown upgrade as a separate issue. I'm happy with the work around for now.
