### ISSUE TITLE
First radio button doesn't work when rendered on server side

### ISSUE THREAD

**Issue by opensourcegeek** [govuk-react/govuk-react#453]
I'm trying to render Radio components on server side using `emotion-server` (`renderStylesToString` API call). This results in emotion adding `style` tags in the first input tag, which means the selector `:checked + span::after` doesn't work as the immediate sibling element to `input` is a `style` element now.

Is there a way to work around it? Quickly skimming through I cannot find a straight forward alternative, any suggestions would be greatly helpful.

**Comment by opensourcegeek** [comment]
Following code seems to workaround the issue (moved to `~` from `+`)

```jsx
const SelectRadio = styled(Radio)({
  '& input:checked ~ span::after': {
    opacity: 1
  },
  '& input:focus ~ span::before': {
    boxShadow: `0 0 0 4px ${YELLOW}`     
  },
  '& input:disabled ~ span': {
    opacity: '.4',
    pointerEvents: 'none'     
  }
});
```
Do you think change to CSS selector is useful as a separate PR?

**Comment by opensourcegeek** [comment]
@penx Any comments on work around/PR?

**Comment by penx** [comment]
@opensourcegeek I need to reproduce the issue and have a think, will try tonight or tomorrow. A codesandbox or GitHub repo that reproduces issues would be handy so there isn't a barrier to recreating :-)

**Comment by penx** [comment]
Our checkboxes should be brought inline with the following CSS:

https://github.com/alphagov/govuk-frontend/blob/master/src/components/checkboxes/_checkboxes.scss

And the following template:

https://github.com/alphagov/govuk-frontend/blob/master/src/components/checkboxes/template.njk

This doesn't seem to use `~` so I imagine may fix the issue

**Comment by penx** [comment]
Our radios should be brought inline with the following CSS:

https://github.com/alphagov/govuk-frontend/blob/master/src/components/radios/_radios.scss
And the following template:

https://github.com/alphagov/govuk-frontend/blob/master/src/components/radios/template.njk

This doesn't seem to use `~` so I imagine may fix the issue

**Comment by penx** [comment]
I believe we are tracking the following CSS:

https://github.com/alphagov/govuk-frontend/blob/4b3c08191297405c1cecabc5d0aceb9ce19b575f/src/components/radios/_radios.scss#L121-L123

...so doing something different would bring us away from govuk-frontend which I'd rather not do if it can be avoided.

**Comment by penx** [comment]
@opensourcegeek can you make a basic github repo that reproduces the issue after an `npm install` and `npm start`?

**Comment by penx** [comment]
also do you get the same issue when using next.js? You can try it out on codesandbox, I had started something here https://codesandbox.io/s/1q99004kml

Also a screenshot of what "not working" looks like would help so I can be sure I'm recreating the issue correctly

**Comment by penx** [comment]
Just seen you have a reproducable example in another ticket. Will try check that out tomorrow

**Comment by opensourcegeek** [comment]
@penx thanks - the problem is this happens only when rendered on server side, we came across it when testing no JS journey. I don't think the project I've linked you will work as it's vanilla create-react-app.

I'm happy to set a project for you which could help you diagnose the problem. But the issue is when rendering on server side with emotion-server it adds `style` tags that disturbs the sibling selector in govuk-frontend. So one option is to find a way to get emotion-server to not do that, but my experience with emotion server is very minimal so I couldn't find a work around that way. The other option was to change the selectors so that it still works if it's not immediate sibling in DOM. This does the trick for now, but your suggestions to work around this issue using whatever approach would be very useful.

**Comment by opensourcegeek** [comment]
@penx please checkout https://github.com/opensourcegeek/govuk-react-playground, if you have any issues please let me know.

**Comment by penx** [comment]
Pretty sure using `extractCritical` would solve this:

https://emotion.sh/docs/ssr

**Comment by opensourcegeek** [comment]
Thanks @penx - I'll give that a try and let you know

**Comment by penx** [comment]
We're no longing using emotion so closing this issue as stale, please reopen with an example if it's still an issue
