### ISSUE TITLE
Header should be called Heading

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#454]
To be in line with govuk-frontend, Header should refer to the Top Nav:

https://design-system.service.gov.uk/components/header/

We can use Heading to refer to our title/H1 components instead, freeing the name 'Header' up for using for the top nav in future.

Once Header is renaming Heading, we should mark Header as deprecated.
(as long as we can un deprecate it in future)

**Comment by stevesims** [comment]
See #569 for notes about deprecation support.

Wondering if we should consider writing automated scripts to ease migration for renamed components.  See https://github.com/reactjs/react-codemod
