### ISSUE TITLE
Upgrade to emotion 10

### ISSUE THREAD

**Issue by sastels** [govuk-react/govuk-react#485]
We've been using this package for a bit over here in Canada 👍. Any thoughts about upgrading `emotion` to version 10?

**Comment by penx** [comment]
I've [asked on emotion-slack](https://emotion-slack.slack.com/archives/C64D9NR24/p1544478002046600), but as far as I can see the 'incremental process' is for updating an app - when it comes to a library you have to make the jump of either support emotion 9 OR emotion 10. They mention using `@emotion/styled` as an incremental change but this is not available for emotion 9.

I have a few concerns:

1. I'm not clear on why they have done this. Changing the API is a problem for libraries like this. I'm not clear on what the benefits of this new structure are. I'm also not sure why this couldn't have been done in a way that was backwards compatible.

2. Migrating to styled-components would possibly be a simpler change for all involved. We should assess which would be the better option

3. When we upgrade, peer projects and related libraries would need to be updated at the same time. We should encourage input from upstream projects - @Djangofs @Joe-Brady @jsrobertson @stevesims

**Comment by penx** [comment]
As far as I can tell, it should be possible to use `eslint-plugin-emotion` to automate the whole update other than the use of keyframes in the Spinner icon component.

We could also release this as 0.4.x and then backport any fixes/features to 0.3.x if upstream projects require them.

**Comment by penx** [comment]
We will likely move to styled-components instead 
https://github.com/govuk-react/govuk-react/issues/520
