### ISSUE TITLE
Update checkboxes to match govuk-frontend

### ISSUE THREAD

**Issue by jsrobertson** [govuk-react/govuk-react#496]
Checkboxes height and widths need updating from 38px to 40px.  The focus outline also needs to be 3px instead of 4px.

See https://github.com/alphagov/govuk-frontend/blob/master/src/components/checkboxes/_checkboxes.scss for reference.

**Comment by jsrobertson** [comment]
Raised https://github.com/govuk-react/govuk-react/pull/497

**Comment by penx** [comment]
Fixed by #497
