### ISSUE TITLE
Consider switching to styled-components

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#520]
Recently we've tried to put some work into upgrading to Emotion 10 as suggested in #485.  Unfortunately for a component library such as this, the upgrade path is not clean and it would be a "big bang" update, dropping backward compatibility to Emotion 9.  Whilst progress was made towards this in #491 some significant difficulties were encountered and work has currently stalled.

More recently during work to improve our compatibility with govuk-frontend, some serious problems were encountered when attempting to replicate the styling of list components.  In brief, there is a style rule to ensure that lists placed within lists get a `margin-top: 10px` style set - in principle this is a simple rule to implement however, long story short, we could not get it to work reliably/properly using Emotion.

Part of the problem encountered is illustrated in [this sandbox example](https://codesandbox.io/s/k08pmjrl5r).  (NB this example uses Emotion 10, but the same issue occurs in Emotion 9.)  The problems however were wider and deeper than this simple example, with additional issues caused by wrapping our components with the `withWhiteSpace` HOC.

Preliminary investigations seem to indicate these problems do not exist with styled-components, as can be seen by changing the above sandbox example to use styled-components.

As moving to Emotion 10 is proving problematic, and we are finding additional issues with Emotion, we should consider switching to styled-components

**Comment by penx** [comment]
For posterity, and to avoid further searching around for the unresolvable issue we had with emotion, this was initially discussed on emotion slack and later summarised here:

> you are referring to & being based on the hashed styles rather than based on the component identity. This is by design and won't change.

https://github.com/emotion-js/emotion/issues/2223#issuecomment-830624251
