### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by jsrobertson** [govuk-react/govuk-react#526]
Spoken with @penx and will be raising a PR shortly for the footer component (https://design-system.service.gov.uk/components/footer/).

**Comment by jsrobertson** [comment]
We were in need of a govuk footer component which I have made and we're now using and can be [seen here](https://ministryofjustice.github.io/new-nomis-shared/?selectedKind=Footer&selectedStory=With%20navigation%20links&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

It currently accepts `navigation`, `meta` and `children` as props.  

`navigation` is an array and `meta` is an object and both accept data in the same structure as mentioned on https://design-system.service.gov.uk/components/footer/ and `children` will display a `PropType.node` in the area where it says "Built by the Government Digital Service` [here](https://design-system.service.gov.uk/components/footer/full/index.html)

I can raise a PR based on the above, or can look to change it so you can specify React components as the children e.g. 

```jsx
<Footer>
  <Footer.Navigation>
    <Footer.Section>
      <Footer.Heading>
        Services and information
      </Footer.Heading>
      <Footer.Links>
        <Footer.Link href='/normal-link'>Normal Link text</Footer.Link>
        <Footer.Link linkType={Link} to='/router-link'>Router Link text</Footer.Link>
      </Footer.NavigationLinks>
    </Footer.Section>
  </Footer.Navigation>
  <Footer.Meta>
    <Footer.MetaLinks>
      <Footer.Link href='/normal-link'>Normal Link text</Footer.Link>
      <Footer.Link linkType={Link} to='/router-link'>Router Link text</Footer.Link>
    </Footer.MetaLinks>
  </Footer.Meta>
</Footer>
```

This will be my first new component PR so any thoughts will be appreciated.

**Comment by penx** [comment]
The way I've been approaching `<Footer.Navigation>` vs a prop called navigation on govuk-frontend-react is:

- if children is specified, use that
- if not, look for items (or similar) props and use them

You can see this in action here:

https://github.com/penx/govuk-frontend-react/blob/master/src/components/date-input/index.js

```jsx
        children || (
          <MergeFocus onBlur={onBlur} onFocus={onFocus} keys={items.map(({ name }) => name)}>
            {mergeFocus => (
              <MergeValues value={value} onChange={onChange} keys={items.map(({ name }) => name)}>
                {mergeValues => (
                  <>
                    {items.map(
```

Perhaps that approach would work here too?

**Comment by stevesims** [comment]
I'm quite keen on the "construction kit" approach myself.

I hadn't really looked at the footer component before.  The myriad of different examples does to me push towards a construction kit to allow for maximum flexibility.  I'd anticipate/expect to make use of existing components as much as practical, and demonstrate by example (in storybook) how to construct different formats of footer.

With that in mind, if there's ways in which existing components could be improved, or other components that we should add to aid in this effort, please let me know.

(For example, with the move to styled-components I expect that I will soon add an `Anchor` component, and deprecate the `asAnchor` HOC, as it will be possible to use the styled-components `as` prop to allow an `Anchor` to be a react-router `Link`.)

**Comment by penx** [comment]
We should have React Router and possibly Reach Router examples in storybook to prove this is actually possible, including where [NavLink](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md) may be needed to detect a different style to represent the page you're currently on (does the footer do this anywhere?)

**Comment by penx** [comment]
I wrote a react-router story for the Header in govuk-frontend-react (though I'm no longer convinced that a separate fixtures file is good, at least for unit tests)

https://github.com/penx/govuk-frontend-react/blob/master/src/components/header/stories.js
https://github.com/penx/govuk-frontend-react/blob/master/src/components/header/fixtures.js

**Comment by penx** [comment]
In the Header I don't allow for 'items' at all as I knew the issues this may cause with routers/links - but swaying towards providing both options now.

**Comment by stevesims** [comment]
minor note - having just checked out their code, as govuk-frontend uses `link` our component will be called `Link`, and not `Anchor` - which would mean you'll end up doing something like this:
```jsx
import Link from '@govuk-react/link';
import { Link as RouterLink } from 'react-router';

export default () => (<div>
  Some content here with a <Link as={RouterLink}>link</Link>
</div>);
```

**Comment by jsrobertson** [comment]
Apologies that this has been a bit quiet.  I've got some time to pick this up again now so have started working through it again. 

Thanks for the above comments, will take them onboard!

If you were using the footer component would you expect the default `<Footer />` to render as [it does here](https://design-system.service.gov.uk/components/footer/default/index.html) with the OGL and Copyright logos, or would you expect that to be an optional child component?
