### ISSUE TITLE
installing 0.6.0 gives following error

### ISSUE THREAD

**Issue by tuqire** [govuk-react/govuk-react#540]
seems the latest version (`0.6.0` I think) is broken. Keep getting following error when I run `npm install -S govuk-react`. Running `npm install -S govuk-react@0.5.1` worked fine.

```npm ERR! code E404
npm ERR! 404 Not Found: @govuk-react/details@^0.6.0-alpha.1```

**Comment by penx** [comment]
what did you `npm install`? We're in the process of releasing the alpha.1 version right now, one of the sub packages likely hasn't published yet.

**Comment by penx** [comment]
Ok there's 2 problems here:

1. `npm install -S govuk-react` is installing an alpha version for some reason. We'll look in to why this is. We were expecting the 0.5.1 would be the latest version via an npm install until we came out of alpha/prerelease.

2. we were in the process of an alpha release so there were missing packages when you tried to install.

Note 0.6 uses styled-components wheras 0.5 uses emotion. We still have docs to update about this but it's more or less the same setup process.

**Comment by penx** [comment]
All packages are release now so you can use the 0.6.0-alpha.1 if you want - or stick with 0.5.1

**Comment by tuqire** [comment]
thanks, closing ticket.

**Comment by penx** [comment]
turns out npm publish tags prerelease as 'latest' and `npm install` defaults to latest.

> In npm 3.4.1, the default behavior changed: instead of the star range, npm now uses the “latest” tag, which is equivalent to:
https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

We've reverted the 'latest' version on npm back to 0.5.1, you can still opt in to the alpha by specifying it
