### ISSUE TITLE
Readme references `0.6.0` release and not `0.5.2`

### ISSUE THREAD

**Issue by tuqire** [govuk-react/govuk-react#561]
Hi,

It appears the current readme is referring to a release of this lib which is in alpha. The default version installed (`0.5.2`) uses emotion and not styled components I think.

**Comment by stevesims** [comment]
Yes - we're an an interim stage right now and have updated the current readme to reflect the direction we're going in, rather than the current `latest` release.  It thus matches the current `next` release.

We're hoping to finalise 0.6.0 and release it soon - hopefully within the next week
