### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#578]
Currently govuk-react is strictly plain GDS in its appearance, with no theming support provided.

govuk-frontend allows for theming via setting sass variables - their sass files define defaults, so if variables of the same name get set before their sass loads then those new values will override.  Owing to how our styling works, we can't follow this mechanism/model directly.

We're using styled-components, which provides [theming support](https://www.styled-components.com/docs/advanced#theming) via a `ThemeProvider` component.  We could look to provide theming support via this mechanism.

The idea is that we should provide a default theme (and a default `ThemeProvider`) for govuk-react.  Components should derive values for styles from the current theme for the component, with a fallback of the default theme (see styled-component docs).  We would need to document the govuk-react theme format, and provide demonstrations for how the theme can be augmented/overridden.

One significant challenge in supporting theming will be how to support it in styling lib functions.  This will need some thought.

**Comment by penx** [comment]
Due to the overhead of maintaining this, without additional maintainers and/or sponsors I think we should close this, @stevesims ?

**Comment by stevesims** [comment]
yeah - given that we don't really have the time to work on this, we should probably close this

in a later component library I created after govuk-react we added supported for theming via styled-system, which provided support for many of the kind of styling-lib function features we'd written here.  migrating to that tho would be a lot of work, and possibly make syncing with govuk-fronend harder
