### ISSUE TITLE
Re-arrange storybook stories

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#589]
We currently have organised our storybook stories to have "Examples" folders underneath components.  This is done by having a single `storiesOf` declaration for the component itself, and then a separate `storiesOf` declaration for the examples.

Unfortunately as Chromatic just takes the leaf name in `storiesOf` declarations, this approach results in lots of "Examples" in Chromatic that are not tied to their corresponding component.

We should instead add examples to the `storiesOf` declaration for the component.

To facilitate this we'd need to change how we attach documentation to components.  In our `stories.js` files we'd need to remove this line:
```jsx
stories.addDecorator(WithDocsCustom(ReadMe));
```
and instead on our primary/default story do something like this:
```jsx
stories.add(
  'Component default',
  WithDocsCustom(
    ReadMe,
    () => (
      <BackLink goBack={action('go-back')}>{text('Children', 'Back')}</BackLink>
    ),
  ),
);
```

**Comment by stevesims** [comment]
As part of this we may wish to reconsider how we name and order our stories within storybook

We may also wish to consider adding in a README panel using the `withReadme` feature of `storybook-readme` to allow the documentation to be able to remain visible for all example stories.

**Comment by penx** [comment]
Current plan (will edit this post):

- The first story for any component is ComponentName/Component and shows basic example
  - Docs will be on basic example initially but will move to Docs tab
- The second story for any component is Playground and contains knobs or any other addons for experimentation
- All subsequent stories are specific use cases/fixtures for the purpose of edge case documentation and regression testing
