### ISSUE TITLE
Chromatic capture of stories wrapped in <Fragment>

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#591]
We have a few stories in our storybook where their content is wrapped in a `<Fragment>`. Whilst these stories display perfectly in Storybook, Chromatic currently only captures the first component within the fragment.

This issue has been reported to Chromatic.

The work-around is to not use `<Fragment>` to wrap content in our stories but to instead use a `<div>`.

**Comment by penx** [comment]
Chromatic seems to have resolved this, TopNav is a fragment with 2 elements and renders fine in Chromatic now without a wrapper

https://www.chromatic.com/component?appId=5ad61aab7f00090020dfdba8&name=Page%2FTopNav%2FExamples&buildNumber=1216&specName=everything+with+9+nav+items
