### ISSUE TITLE
Small Checkbox and Radio

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#597]
For non-public-facing UK gov systems smaller sized input elements, especially checkbox and radio components, are often supported.  Examples of these can be found in the Home Office Design System:
https://home-office-digital-patterns.herokuapp.com/components/checkboxes
https://home-office-digital-patterns.herokuapp.com/components/radios

We should consider ways of adding support for such customisation.

There are potentially three options here:

1) Add a `small` prop that supports a (fixed) small size to these components
2) Add support for theming (see #578), and use that to support size variations
3) Have the atom (un-labelled checkbox/radio) exported from the component and used via a prop, allowing it to be re-styled

Or potentially some combination of all three options.

**Comment by stevesims** [comment]
Home Office sass files with these alternate designs can be found here:
https://github.com/UKHomeOffice/design-system/tree/master/app/assets/sass/components

**Comment by penx** [comment]
govuk-frontend now provides small radio options:

https://design-system.service.gov.uk/components/radios/small/index.html

**Comment by rottitime** [comment]
I have developed an update for this . I have also added type support as noticed `Size` is something we use for many elements

Can someone please review my PR?
https://github.com/govuk-react/govuk-react/pull/1193
