### ISSUE TITLE
problems with jest config

### ISSUE THREAD

**Issue by dsm23** [govuk-react/govuk-react#615]
describe.only and test.only appear not to work

**Comment by stevesims** [comment]
ok - so - the thing with Jest is that it runs things in parallel, and the documentation isn't entirely clear about what that means.

The reality is that `describe.only` and `test.only` apply *only* to the single file in which they're used.  The documentation for `test.only` makes this clear, but that's not the case for `describe.only`.

If you want to run unit tests only for a single component then you'd need to do something like `yarn test:unit components/button`

Some discussion on this can be found here:
https://github.com/facebook/jest/issues/4414
