### ISSUE TITLE
Use @storybook/addon-docs instead of storybook-readme (or as well as?)

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#621]
We currently use storybook-readme to show the readme files for components within storybook.

This was proposed in #212 and implemented in #300.

This is great, but has a flaw in that it is applied to the "default" story for a component.  Additionally the use of the component is illustrated solely via examples written in-line in comments in the component source and written out into the readme files when docs are generated.

The [@storybook/addon-info](https://www.npmjs.com/package/@storybook/addon-info) plugin has an advantage over our current approach in that it can display the source code for any/all of our examples.

We should consider adopting addon-info for our stories.  As part of that we should consider a few things:
* should this apply to "example" stories only, i.e. leave the "Component Default" stories as-is using readme?
* do we want this info documentation in-line on the page, or (as per their default) or click-to-view
* can it provide full documentation as per our current readme files?
* if yes, should we remove our existing readme files?

**Comment by stevesims** [comment]
The docs for addon-info imply that @storybook/addon-info will show documentation in react-docgen format, which is how we are documenting components, however in experiments I've not been able to make this work.  (This included ensuring that `babel-plugin-react-docgen` had been added to the babel configuration.)

**Comment by penx** [comment]
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-info-addon-notes

replaced with addon-docs

**Comment by stevesims** [comment]
yup - addon-docs is good - I've used it in another component library - used MDX format docs, which allowed documentation to form part of the storybook stories, and props got automatically documented from their typescript types.

definitely worth investigating moving to use addon-docs.  we may want to consider how the rest of our documentation works too and move away from our custom scripting, given the potential advantages it brings

**Comment by penx** [comment]
Fixed in #856
