### ISSUE TITLE
Can we submit a pull request without a .gov email?

### ISSUE THREAD

**Issue by jlrodney** [govuk-react/govuk-react#664]
I am getting a "permission denied" when I follow the [contributing](https://github.com/govuk-react/govuk-react/blob/master/CONTRIBUTING.md) steps,
Thanks.

**Comment by penx** [comment]
What step?

You should:
1. Create a fork of govuk react on your own github account
2. Create a branch on your fork for the planned feature or bug fix
3. When done, push to this branch and open a PR using the GitHub website

**Comment by jlrodney** [comment]
Thanks, didn't realize I needed to make a fork. I thought I could just make a branch and then open a pull request 🤦.
