### ISSUE TITLE
Details component is not hiding information on IE

### ISSUE THREAD

**Issue by abidur-rehman** [govuk-react/govuk-react#699]
Details component is not able to hide information, as it should be on Microsoft browsers. Tested on IE11 and Microsoft Edge 42. Details are always displayed.
It's working fine on Chrome.

**Comment by yeahfro** [comment]
The issue here is that `<details>` is not supported in IE or Firefox. To get around this problem you will need to use a details polyfill. We have a dependency on `govuk-frontend` so we inadvertently use their details polyfill.
