### ISSUE TITLE
Importing Link no longer working (and example used in the docs)

### ISSUE THREAD

**Issue by MartinDM** [govuk-react/govuk-react#710]
In attempting to render a `Link` using the example in the Readme and in the [Storybook](https://govuk-react.github.io/govuk-react/?path=/story/typography-link--component-default), there's an error:
```'Link' is not defined  react/jsx-no-undef```

Perhaps the ReadMe example outdated? Could use some guidance on using this component.
Is there a recommended way to link a <Button> for example, using this method?

**Comment by stevesims** [comment]
Hi @MartinDM 

Link seems to work for me - here's a quick example codesandbox: https://codesandbox.io/s/strange-shadow-vrgez

**Comment by Loque-** [comment]
I'm going to close this, but if you believe it's still an issue feel free to re-open, and if possible link a codesandbox with the issue demonstrated.
