### ISSUE TITLE
SearchBox

### ISSUE THREAD

**Issue by NistrumCain** [govuk-react/govuk-react#712]
Hey, if Searchbox doesnt accept any sort of onclick function, how are you supposed to use it?

**Comment by Loque-** [comment]
Hey there!

You can click into the Searchbox fine: https://govuk-react.github.io/govuk-react/?path=/story/form-searchbox--component-default 

What is the problem you are having?

**Comment by bguyan** [comment]
Hey, Thanks for the speedy reply! i mean if i am using the component how do i pass in a function for clicking on the search to perform, or when you hit enter for exampe?

**Comment by bguyan** [comment]
also you know the heroku app is dead?

**Comment by Loque-** [comment]
I don't believe you can do this with that component currently, kind of tricky to design also as you'd need to surface properties from two unique elements. If you want to do this, I'd look at the source for the searchbox and implement it from there; https://github.com/govuk-react/govuk-react/blob/master/components/search-box/src/index.js. Hope that helps you!

I can only see two heroku links in the readme.md and both are still active (although not maintained by maintainers of this library), what link are you talking about?

**Comment by NistrumCain** [comment]
then how are you intended to use the search box? like how can i actually use it to search stuff?

**Comment by penx** [comment]
Agreed it looks like this hasn’t yet been implemented. 

I would think the simple route would be to have a button prop and input prop that are spread on to the button element and input element accordingly. 

Open to someone raising a PR to resolve this

**Comment by Loque-** [comment]
I believe it is designed to be used with react-final-form, I don't have an example to hand though. 

I see the broken Heroku link in the readme for the searchbox, this is just for the reference to the component from GDS, but I should update it and remove it.

Edit; ah oki, yea I could see that working

**Comment by NistrumCain** [comment]
yeah. my intention was to use a sort of onClick prop passed down into the component and i can pass in my function. i wouldnt mind looking to doing it, not sure what the policy to contribution is?

**Comment by Loque-** [comment]
https://github.com/govuk-react/govuk-react/blob/master/CONTRIBUTING.md

**Comment by NistrumCain** [comment]
hahah, Thanks! also sorry if i came across badly, was mostly expecting that i was just missing something really obvious! thanks a ton for taking the time to get back to me!

**Comment by Loque-** [comment]
No, no problem at all - thanks for the question and if theres anything we can do to help with contributing let us know!
