### ISSUE TITLE
ESLint error when importing components: @govuk-react/[component]' should be listed in the project's dependencies

### ISSUE THREAD

**Issue by brightpixels** [govuk-react/govuk-react#714]
I am importing this component as per storybook: `import Input from '@govuk-react/input';` which works fine but I am getting EsLint error: 
````
'@govuk-react/input' should be listed in the project's dependencies. Run 'npm i -S @govuk-react/input' to add iteslint(import/no-extraneous-dependencies)
````

How to best deal with this type of error?

**Comment by dsm23** [comment]
This looks like a problem your end. `@govuk-react/input` is a dependency of `govuk-react`. I'm betting you only have govuk-react declared in your `package.json`. You can import the `Input` component from `govuk-react` like this: 

```
import { Input } from 'govuk-react';
```

How ever I would recommend instead using `InputFIeld` which is a higher level abstraction of `Input` and provides great support for `react-final-form`.

**Comment by brightpixels** [comment]
So given I want to use the input component, what packages do I need to install? Both govuk-react and @govuk-react/input? Sorry I am little confused.

**Comment by Loque-** [comment]
It looks like you need to ensure the dependancy `'@govuk-react/input' ` is listed in your projects dependancies (`package.json`) as per the error message, maybe this intro on dependancies might help? https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

As you are only using `@govuk-react/input` you only need to ensure this package is in your projects dependancies. If you run the commang in the error message it will add it to your package.json file for you, or you could add it manually and then run `npm install` to install the dependancies listed in package.json.

If you wanted to use multiple elements from `govuk-react` you only need to make sure that is in your dependancies and that you import from there, as per the example in dsm23's comment.

I am going to close this issue as it is not an issue linked to this repository. If you think it is a problem with the repository please do comment again with a codesandbox example of the issue so we can help.

Cheers!
