### ISSUE TITLE
Forking/publishing

### ISSUE THREAD

**Issue by simon-says-test** [govuk-react/govuk-react#740]
Hi,

We've forked this repository to do some accessibility improvements. We would like to eventually submit a PR but, due to tight timescales, were hoping to publish our fork to npm as a private package as a stopgap solution. When we've tried this, the references to components don't work due to them still being located in the component folder and not available from index.js. Is there a step I'm missing in the npm publishing process that occurs on your CI server? 

I did:
```sh
yarn
yarn build
yarn pack
npm publish <filename>
```

Apologies if this is a daft question - I'm not overly familiar with package publishing. We will look into meeting PR requirements in the meantime anyway but any help would be appreciated. The documentation is gret but would be good to have instructions on how to publish a fork for these scenarios, although I might be asking a bit much here I appreciate.

Many thanks

**Comment by penx** [comment]
As this is a monorepo, each component needs to be published individually.

Have you read this?

https://github.com/govuk-react/govuk-react/blob/master/CONTRIBUTING.md#releasing

**Comment by penx** [comment]
The next thing to read would be the travisPublish.sh script that runs on CI:

https://github.com/govuk-react/govuk-react/blob/master/scripts/travisPublish.sh

**Comment by simon-says-test** [comment]
Thanks very much - the pieces of the puzzle are starting to slot into place in my head now. Much appreciate the quick response.
