### ISSUE TITLE
Remove use of PropTypes.any and TypeScript any

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#794]
There are some uses of `PropTypes.any` in the code which, with the rules we now have for eslint, *should* cause a linting error.  For now the rules have been disabled, but we should revisit these items and set better, more appropriate, prop types.

- Remove uses of PropTypes.any
- Remove use of TypeScript `any`
- enable TypeScript lint rule that was disabled in #952 (see #794)

**Comment by penx** [comment]
@marksy @stevesims either of you fancy picking this one up?
