### ISSUE TITLE
Remove JSX Wrappers from documented styled components

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#81]
In https://github.com/penx/govuk-react/pull/79 some components have been renamed from e.g. `Button` to `GButton` (edit, now `Styled*`) and then wrapped with a JSX wrapper so that they are picked up by react-docgen.

We ideally don't want to dictate code structure due to documentation generation so want to look in to another solution in the future.

https://github.com/reactjs/react-docgen/issues/256

**Comment by Loque-** [comment]
Not sure I fully understand this one, has it been resolved? I cannot see this issue in the repo currently.

**Comment by penx** [comment]
Yes this issue is still present in the repository,

e.g.

```jsx
const ErrorText = props => <StyledError {...props} />;
```

This is redundant code. We could just export StyledError but need to wrap it with JSX so that it is picked up by react-docgen.

Doing a find on ` = props => <Styled` throughout the whole project should show all places this is happening.

**Comment by penx** [comment]
Related

https://github.com/reactjs/react-docgen/issues/256
https://github.com/jquense/react-docgen-styled-resolver/issues/1

**Comment by penx** [comment]
react-docgen-styled-resolver would be good but I haven't been able to get it to work

https://github.com/jquense/react-docgen-styled-resolver/issues/1

**Comment by penx** [comment]
We now have docs appearing in Storybook via their docs addon.

https://github.com/storybookjs/storybook/tree/master/addons/docs
https://github.com/storybookjs/storybook/tree/master/addons/docs/src/lib/docgen

In part, they seem to be using

https://github.com/storybookjs/babel-plugin-react-docgen

**Comment by penx** [comment]
Unfortunately storybook's docs generation relies on the same code and has the same issue

https://github.com/storybookjs/storybook/issues/8279

After converting to typescript, Storybook uses react-docgen-typescript, but this doesn't seem to render any docs at all so I have reverted to react-docgen as described at:

https://gist.github.com/shilman/036313ffa3af52ca986b375d90ea46b0

**Comment by penx** [comment]
As we are reliant on Storybook generation, and I don't think we can configure Storybook to use a custom resolver, I don't think this is going to be fixable even if we were to write a custom resolver, until storybookjs/storybook#8279 is resolved.

**Comment by penx** [comment]
This was resolved during the transition to TypeScript
