### ISSUE TITLE
Add "Why is this a monorepo?" to the readme

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#824]
To cover:

- ability to upgrade govuk-react and still use older components, e.g. deprecated ones
- in a large application where parts are reliant on an older component API but you aren't able to refactor and don't want to hold back from upgrading

# Why is this a monorepo?

Components are published to npm independently. This means users have the ability to upgrade govuk-react and still use older components.

This is particularly relevant in a large application where:

- some code is reliant on a component that has either been deprecated or had breaking changes 
- you aren't able to refactor the existing code, e.g. it is a large job or managed by another team
- you don't want to hold back from upgrading to the newest version of govuk-react

e.g. for DateField, you import it separately as follows:

```js
import { H1, Paragraph } from 'govuk-react';
import DateField from '@govuk-react/date-field';
```

Then in your package.json, you can update govuk-react, but specify the older version of '@govuk-react/date-field'.

**Comment by penx** [comment]
cc @stevesims if there's anything you want to add

**Comment by penx** [comment]
this is briefly touched on in https://github.com/govuk-react/govuk-react/blob/master/CONTRIBUTING.md but I want to add it to the main readme

**Comment by penx** [comment]
Also related https://github.com/govuk-react/govuk-react/issues/481#issuecomment-442953277

**Comment by stevesims** [comment]
for me, the decision to make govuk-react a mono-repo was a great one, and gives very significant advantages

frustratingly it's also advantages that I failed to convey quite well enough when building the next component library I made after govuk-react - the powers that be at that organisation had some bad experiences in using monorepos.  there were other significant battles to fight, so unfortunately I had to leave that

so yes - pushing the plusses and advantages of using a mono-repo should definitely go into the readme 😀
