### ISSUE TITLE
CRA app breaks after adding the Paragraph component

### ISSUE THREAD

**Issue by g1st** [govuk-react/govuk-react#860]
After fresh CRA install and adding `govuk-react` with `styled-components` packages. If `Paragraph` component is used app breaks with the following error message:

```
./node_modules/@govuk-react/paragraph/es/index.js
Module not found: Can't resolve 'react-markdown' in 'C:\Users\user\code\myApp\node_modules\@govuk-react\paragraph\es'
```

Now locally for me the issue still persist even if I install `react-markdown`. In the [Sandbox example](https://codesandbox.io/s/cranky-dawn-y337q?file=/src/App.js) there is no error but the paragraph text is not rendered at all. 

**To Reproduce**
Please see [Code Sandbox example](https://codesandbox.io/s/cranky-dawn-y337q?file=/src/App.js)

**Expected behavior**
I should see a paragraph text rendered on the screen.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19042.985
 - Browser Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by penx** [comment]
Thanks for reporting this.

I need to look further in to the cause of this, but I notice if you downgrade to react-markdown 3.6.0 it seems to resolve the issue.

**Comment by penx** [comment]
Ok it works up until react-markdown 6, from what I can see.

I will be releasing govuk-react 0.9 soon, which will have react-markdown as a direct dependency (#846), which will prevent this from happening.

Please let me know if you have any further issues.

**Comment by g1st** [comment]
Hi, thanks for a new release. But it seems that I can't upgrade to 0.9.0:

```
PS C:\Users\user\myApp> npm i govuk-react@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@govuk-react%2fglobal-style - Not found
npm ERR! 404
npm ERR! 404  '@govuk-react/global-style@^0.9.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'govuk-react'
```

**Comment by penx** [comment]
@g1st thanks, give me a minute I'll try get that released now

**Comment by penx** [comment]
@g1st please can you try again?

**Comment by g1st** [comment]
Installed successfully and everything seems working fine! Thanks!
