### ISSUE TITLE
Storybook's addon-knobs Is deprecated

### ISSUE THREAD

**Issue by stevesims** [govuk-react/govuk-react#908]
The latest version of @storybook/addon-knobs informs that it has been deprecated in favour of addon-controls

**Comment by stevesims** [comment]
we may wish to delay updating this until after we've updated our components to use typescript types for props, rather than proptypes - IIRC the automatic doc generation in storybook will automatically pick up quite a few things from those type definitions and include them in controls

**Comment by penx** [comment]
> use typescript types for props, rather than proptypes

I think @marksy may be looking at some TypeScript things and may want to look at this?

May need a ticket for this?
