### ISSUE TITLE
Add typescript declaration

### ISSUE THREAD

**Issue by marvin-42** [govuk-react/govuk-react#941]
**Is your feature request related to a problem? Please describe.**
When I try to use it in typescript project I have error
`Could not find a declaration file for module 'govuk-react'. '/node_modules/govuk-react/lib/index.js' implicitly has an 'any' type. Try 'npm i --save-dev @types/govuk-react' if it exists or add a new declaration (.d.ts) file containing 'declare module 'govuk-react'`

**Describe the solution you'd like**
Create module declaration

**Comment by penx** [comment]
Hi @marvin-42 , thanks for raising this!

We're planning on publishing types in the 0.9.2 release - we have an issue here https://github.com/govuk-react/govuk-react/issues/891

I'll close this as a duplicate, hope that's ok.
