### ISSUE TITLE
Move all CI services from Travis to Drone

### ISSUE THREAD

**Issue by penx** [govuk-react/govuk-react#96]
Now that Drone seems to be working, we should move all Travis services to Drone and delete .travis.yml

**Comment by penx** [comment]
Blocked by caching issues on Drone

**Comment by Loque-** [comment]
It has been suggested that we move to services aligned with UKHomeOffice: https://github.com/UKHomeOffice/application-container-platform-bau/issues/3665#issuecomment-400615838
